services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: datavision
      POSTGRES_USER: datavision
      POSTGRES_PASSWORD: datavision
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
