"""make positions.zone nullable

Revision ID: ded1a257da1a
Revises: f1c46e7a7fb3
Create Date: 2026-07-08 22:59:18.093180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded1a257da1a'
down_revision: Union[str, Sequence[str], None] = 'f1c46e7a7fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'zone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'zone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
