"""add zones_geometry to sources

Revision ID: f1c46e7a7fb3
Revises: c468fb956ec6
Create Date: 2026-07-08 22:27:52.778159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1c46e7a7fb3'
down_revision: Union[str, Sequence[str], None] = 'c468fb956ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('zones_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'zones_geometry')
    # ### end Alembic commands ###
